---
# pyenv setup
- name: Install pyenv
  git:
    repo: https://github.com/pyenv/pyenv.git
    dest: ~/.pyenv
- name: Install pyenv-virtualenv plugin
  git:
    repo: https://github.com/pyenv/pyenv-virtualenv.git
    dest: ~/.pyenv/plugins/pyenv-virtualenv
- name: Install pyenv-update plugin
  git:
    repo: https://github.com/pyenv/pyenv-update
    dest: ~/.pyenv/plugins/pyenv-update
- name: Install pyenv-doctor plugin
  git:
    repo: https://github.com/pyenv/pyenv-doctor
    dest: ~/.pyenv/plugins/pyenv-doctor
- name: Create npm global prefix directory
  file:
    state: directory
    mode: 0755
    path: ~/.npm-global

# nvm & node
- name: Clone NVM
  git:
    repo: https://github.com/nvm-sh/nvm.git
    dest: "~/.nvm"
    version: "v{{ nvm_version }}"
- name: Set npm global config
  ini_file:
    path: ~/.npmrc
    section: null
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  with_items:
    - option: fund
      value: "false"
    - option: init-author-name
      value: "{{ me.name }}"
    - option: init-author-email
      value: "{{ me.email }}"
