---
- name: Configure dotfiles
  hosts: all
  become: false
  roles:
    - { role: common,   tags: always }
    - { role: git,      tags: always }
    - { role: ssh,      tags: always }
    - { role: vim,      tags: always }
    - { role: zsh,      tags: always }
