---
- name: Configure dotfiles
  hosts: all
  become: false
  roles:
    - { role: common,     tags: always }
    - { role: git,        tags: [git] }
    - { role: ssh,        tags: always }
    - { role: vim,        tags: always }
    - { role: langs,      tags: always }
    - { role: zsh,        tags: always }
    - { role: fish,       tags: [fish] }
    - { role: sway,       tags: [desktop]}
    - { role: alacritty,  tags: [desktop]}
    - { role: mako,       tags: [desktop]}
    - { role: waybar,     tags: [desktop]}
    - { role: fontconfig, tags: [desktop]}
    - { role: ncspot,     tags: [desktop]}
