---
# tasks file for zsh
- name: Install zshrc
  file:
      src: "{{ user_local_checkout_dir }}/roles/zsh/files/zshrc"
      dest: "~/.zshrc"
      state: link
- name: Install zsh_functions
  file:
    src: "{{ user_local_checkout_dir }}/roles/zsh/files/zsh_functions"
    dest: "~/.zsh_functions"
    state: link
