---
# tasks file for git
- name: Set gitconfig aliases
  git_config:
      name: "alias.{{ item.name }}"
      value: "{{ item.value }}"
      scope: global
  with_items:
      - { name: co, value: checkout }
      - { name: current, value: rev-parse --abbrev-ref HEAD }
      - { name: count, value: !git shortlog -sn }
      - { name: syncm, value: !git pull upstream master && git push origin master }
      - { name: sync, value: !CURRENT=$(git current) && git pull upstream $CURRENT && git push origin $CURRENT }
- name: Set git color settings
  git_config:
      name: "color.{{ item.name }}"
      value: "{{ item.value }}"
      scope: global
  with_items:
      - { name: diff, value: auto }
      - { name: status, value: auto }
      - { name: branch, value: auto }
      - { name: ui, value: true }
- name: Set git core settings
  git_config:
      name: "core.{{ item.name }}"
      value: "{{ item.value }}"
      scope: global
  with_items:
      - { name: excludesfile, value: "~/.gitignore" }
      - { name: editor, value: nvim }
- name: Set git user settings
  git_config:
      name: "user.{{ item.name }}"
      value: "{{ item.value }}"
      scope: global
  with_item:
      - { name: name, value: Kyle Laker }
      - { name: email, value: kyle@laker.email }
      - { name: signingkey, value: 98351AD5ED619EDA357EC111540AD26362223BB3 }
- name: Sign commits by default
  git_config:
      name: commit.gpgsign
      value: true
      scope: global
- name: Set push settings
  git_config:
      name: "push.{{ item.name }}"
      value: "{{ item.value }}"
      scope: global
  with_items:
      - { name: default, value: simple }
      - { name: gpgsign, value: true }
- name: Set various git settings
  git_config:
      name: "{{ item.name }}"
      value: "{{ item.value }}"
      scope: global
  with_items:
      - { name: apply.whitespace, value: nowarn }
      - { name: mergetool.keepBackup, value: false }
      - { name: difftool.prompt, value: false }
      - { name: help.autocorrect, value: 1 }
- name: Install global gitignore
  file:
      src: "{{ user_local_checkout_dir }}/roles/git/files/gitignore"
      dest: "~/.gitignore"
      state: link
