---
background_image:
  url: "https://www.smashingmagazine.com/files/wallpapers/may-22/the-monolith/nocal/may-22-the-monolith-nocal-3840x2160.png"
  checksum: "sha1:3806b0f40e3d0c239ce2945f767655bdc3c988b9"
grimshot:
  url: "https://raw.githubusercontent.com/swaywm/sway/master/contrib/grimshot"
