---
background_image:
  url: "https://www.smashingmagazine.com/files/wallpapers/apr-22/coffee-morning/nocal/apr-22-coffee-morning-nocal-3840x2160.png"
  checksum: "sha1:916bdc568005c84778218bdd7567283f1596382b"
grimshot:
  url: "https://raw.githubusercontent.com/swaywm/sway/master/contrib/grimshot"
