---
background_image:
  url: "https://www.smashingmagazine.com/files/wallpapers/may-23/moving-montains/nocal/may-23-moving-montains-nocal-3840x2160.jpg"
  checksum: "sha1:276ccbfe23b880d21db792b72f5eeb57f9fe0cdd"
grimshot:
  url: "https://raw.githubusercontent.com/swaywm/sway/master/contrib/grimshot"
