---
# tasks file for x11
- name: Install X11 config files
  file:
      src: "{{ user_local_checkout_dir }}/roles/x11/files/{{ item }}"
      dest: "~/.{{ item }}"
      state: link
  with_items:
    - xsession
    - Xresources
