---
# tasks file for pyenv
- name: Install pyenv
  git:
    repo: https://github.com/pyenv/pyenv.git
    dest: ~/.pyenv
- name: Install pyenv-virtualenv plugin
  git:
    repo: https://github.com/pyenv/pyenv-virtualenv.git
    dest: ~/.pyenv/plugins/pyenv-virtualenv
- name: Install pyenv-update plugin
  git:
    repo: https://github.com/pyenv/pyenv-update
    dest: ~/.pyenv/plugins/pyenv-update
- name: Install pyenv-doctor plugin
  git:
    repo: https://github.com/pyenv/pyenv-doctor
    dest: ~/.pyenv/plugins/pyenv-doctor
