---
- name: Create necessary directories for nvim
  file:
      path: "{{ item }}"
      state: directory
      mode: 0755
  with_items:
    - "{{ nvim_dir }}/autoload"
    - "{{ nvim_dir }}/undodir"
- name: Install vim-plug
  get_url:
      url: "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
      dest: "{{ nvim_dir }}/autoload/plug.vim"
- name: Install vimrc
  file:
      src: "{{ user_local_checkout_dir }}/roles/vim/files/init.vim"
      dest: "{{ nvim_dir }}/{{ nvimrc_file }}"
      state: link
- name: Install vim plugins
  shell: "nvim +PlugInstall +qall"
- name: Update vim plugins
  shell: "nvim +PlugUpdate +qall"
- name: Install vim CoC language support
  shell: "nvim +'CocInstall -sync coc-rust-analyzer coc-pyright coc-json coc-sh coc-tsserver' +qall"
